name: PHPStan

permissions:
  contents: read

on:
  pull_request:
    paths:
      - "app/**"
      - "bin/**"
      - "phpstan.neon"
      - "composer.json"
      - "composer.lock"
      - ".github/actions/setup-php-composer/**"
      - ".github/workflows/phpstan.yml"
  push:
    branches:
      - main
    paths:
      - "app/**"
      - "bin/**"
      - "phpstan.neon"
      - "composer.json"
      - "composer.lock"
      - ".github/actions/setup-php-composer/**"
      - ".github/workflows/phpstan.yml"

jobs:
  phpstan:
    runs-on: ubuntu-latest
    timeout-minutes: 3
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PHP and Composer
        uses: ./.github/actions/setup-php-composer

      - name: Run static analysis
        run: vendor/bin/phpstan analyse --error-format=github
